### ISSUE TITLE
static image hosting

### ISSUE THREAD

**Issue by echarlie** [wuvt/it-tasks#34]
WUVT linx intentionally has a very short file lifetime of 1week. We need a more permanent solution for sharing images to e.g. github tickets. Abusing wuvt-site is an option, as long as we figure out how to audit uploaded files.

**Comment by mutantmonkey** [comment]
GitHub lets you upload images, we have wuvt-site static hosting, and we have Slack. I don't think we really need anything else here, but let's reopen this if we think we need to reevaluate that.
